# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  # Timeout for analysis
  timeout: 5m
  
  # Exit code when at least one issue was found
  issues-exit-code: 1
  
  # Include test files
  tests: true
  
  # Skip directories
  skip-dirs:
    - vendor
    - .git
    - .github
    
  # Skip files
  skip-files:
    - ".*_test.go"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - revive
    
  disable:
    - deadcode
    - structcheck
    - varcheck
    - golint
    - interfacer
    - maligned
    - scopelint
    
linters-settings:
  govet:
    check-shadowing: true
    
  gofmt:
    simplify: true
    
  errcheck:
    check-type-assertions: true
    check-blank: false
    
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
      
  revive:
    confidence: 0.8
    
issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 3
  
  # Show only new issues
  new: false
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - ineffassign
        
    # Exclude known issues
    - path: cmd/fetcher/main.go
      linters:
        - errcheck
      text: "Error return value of .* is not checked"