channels:
  # 監視したいチャンネルを追加
  - id: UCG_oqDSlIYEspNpd2H4zWhw # RehacQ
  - id: UC8yHePe_RgUBE-waRWy6olw # PIVOT
  - id: UCfTnJmRQP79C4y_BMF_XrlA # NewsPicks
  - id: UCBvB2lvfRiuPG_0bKoo_Y5A # さとうさおり
  - id: UCFo4kqllbcQ4nV83WCyraiw # YouTube大学