apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fetcher
spec:
  template:
    spec:
      serviceAccountName: trend-tracker-sa@${PROJECT_ID}.iam.gserviceaccount.com
      containers:
      - image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/trend-tracker-repo/fetcher:${TAG}
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: ${PROJECT_ID}
        - name: MAX_VIDEOS_PER_CHANNEL
          value: "200"
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: youtube-api-key
              key: latest
